const postfix = '_EVENT_LIST';

export const eventListActionTypes = {
    //fetching
    FETCH_EVENT_LIST: `FETCH_EVENT_LIST${postfix}`,
    FETCH_EVENT_LIST_SUCCESS: `FETCH_EVENT_LIST_SUCCESS${postfix}`,
    FETCH_EVENT_LIST_FAILED: `FETCH_EVENT_LIST_FAILED${postfix}`,
    CHANGE_PER_PAGE: `CHANGE_PER_PAGE${postfix}`,
    CHANGE_CURRENT_PAGE: `CHANGE_CURRENT_PAGE${postfix}`,
    CHANGE_SORTED_FIELD: `CHANGE_SORTED_FIELD${postfix}`,
    CHANGE_FILTER: `CHANGE_FILTER${postfix}`,
    EDIT_EVENT_STATUS: `EDIT_EVENT_STATUS${postfix}`,
    EDIT_EVENT_STATUS_SUCCESS: `EDIT_EVENT_STATUS_SUCCESS${postfix}`,
    EDIT_EVENT_STATUS_FAILED: `EDIT_EVENT_STATUS_FAILED${postfix}`,
    TOGGLE_EVENT_DESC: `TOGGLE_EVENT_DESC${postfix}`,
    COLLAPSE_ALL_EVENTS_DESC: `COLLAPSE_ALL_EVENTS_DESC${postfix}`,
    SET_EVENT_TO_EXPAND: `SET_EVENT_TO_EXPAND${postfix}`,
    EXPAND_EVENT_FROM_ALERTS: `EXPAND_EVENT_FROM_ALERTS${postfix}`,
    RESET_FILTER: `RESET_FILTER${postfix}`
};