const postfix = '_APP';

export const appActionNames = {
    FETCH_CURRENT_USER: `FETCH_CURRENT_USER${postfix}`,
    FETCH_CURRENT_USER_SUCCESS: `FETCH_CURRENT_USER_SUCCESS${postfix}`,
    FETCH_CURRENT_USER_FAILED: `FETCH_CURRENT_USER_FAILED${postfix}`,
    LOGOUT_CURRENT_USER: `LOGOUT_CURRENT_USER${postfix}`,
    LOGOUT_CURRENT_USER_SUCCESS: `LOGOUT_CURRENT_USER_SUCCESS${postfix}`,
    LOGOUT_CURRENT_USER_FAILED: `LOGOUT_CURRENT_USER_FAILED${postfix}`
};