const postfix = '_ASSIGNMENT_LIST';

export const assignmentListActionTypes = {
    //fetching
    FETCH_ASSIGNMENT_LIST: `FETCH_ASSIGNMENT_LIST${postfix}`,
    FETCH_ASSIGNMENT_LIST_SUCCESS: `FETCH_ASSIGNMENT_LIST_SUCCESS${postfix}`,
    FETCH_ASSIGNMENT_LIST_FAILED: `FETCH_ASSIGNMENT_LIST_FAILED${postfix}`,
    CHANGE_PER_PAGE: `CHANGE_PER_PAGE${postfix}`,
    CHANGE_CURRENT_PAGE: `CHANGE_CURRENT_PAGE${postfix}`,
    CHANGE_SORTED_FIELD: `CHANGE_SORTED_FIELD${postfix}`,
    CHANGE_FILTER: `CHANGE_FILTER${postfix}`,
    EDIT_ASSIGNMENT_STATUS: `EDIT_ASSIGNMENT_STATUS${postfix}`,
    EDIT_ASSIGNMENT_STATUS_SUCCESS: `EDIT_ASSIGNMENT_STATUS_SUCCESS${postfix}`,
    EDIT_ASSIGNMENT_STATUS_FAILED: `EDIT_ASSIGNMENT_STATUS_FAILED${postfix}`,
    TOGGLE_ASSIGNMENT_DESC: `TOGGLE_ASSIGNMENT_DESC${postfix}`,
    COLLAPSE_ALL_ASSIGNMENTS_DESC: `COLLAPSE_ALL_ASSIGNMENTS_DESC${postfix}`,
    SET_ASSIGNMENT_TO_EXPAND: `SET_ASSIGNMENT_TO_EXPAND${postfix}`,
    EXPAND_ASSIGNMENT_FROM_ALERTS: `EXPAND_ASSIGNMENT_FROM_ALERTS${postfix}`,
    RESET_FILTER: `RESET_FILTER${postfix}`
};