const postfix = '_ASSIGNMENT';

export const actionNames = {

    CREATE: `CREATE${postfix}`,
    CREATE_SUCCESS: `CREATE_SUCCESS${postfix}`,
    CREATE_FAILED: `CREATE_FAILED${postfix}`,

    CREATE_AND_POST_TO_STUDENT: `CREATE_AND_POST_TO_STUDENT${postfix}`,
    CREATE_AND_POST_TO_STUDENT_SUCCESS: `CREATE_AND_POST_SUCCESS${postfix}`,
    CREATE_AND_POST_TO_STUDENT_FAILED: `CREATE_AND_POST_TO_STUDENT_FAILED${postfix}`,

    CREATE_AND_POST_TO_WORK_CLASS: `CREATE_AND_POST_TO_WORK_CLASS${postfix}`,
    CREATE_AND_POST_TO_WORK_CLASS_SUCCESS: `CREATE_AND_POST_TO_WORK_CLASS_SUCCESS${postfix}`,
    CREATE_AND_POST_TO_WORK_CLASS_FAILED: `CREATE_AND_POST_TO_WORK_CLASS_FAILED${postfix}`,

};